# Generated by Django 4.2.11 on 2024-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
